### ISSUE TITLE
Implement online backs up of data

### ISSUE THREAD

**Issue by josephroquedev** [josephroquedev/bowling-companion#101]
Offering online back ups or possibly data transfer / syncing between devices would help prevent major data loss either due to users changing device or accidental data corruption.

**Comment by joseph-roque** [comment]
Now requested by user: " If I could suggest one feature, it would be to enable synching with Google Drive so we don't lose our stats in the event of a lost or damaged device."

**Comment by joseph-roque** [comment]
Escalating to next release because it's probably better to get this done sooner rather than later.

**Comment by joseph-roque** [comment]
Moved to the next version, so that a release can be made in the near future, as this feature is taking longer than expected.

**Comment by joseph-roque** [comment]
Bumping...
