### ISSUE TITLE
Export fails with a generic error

### ISSUE THREAD

**Issue by CaffGeek** [josephroquedev/bowling-companion#254]
**Describe the bug**
When choosing transfer data, export, it just fails, with a generic error message. I have no clue what the actual issue is

**To Reproduce**
1. Go to Transfer Data
2. Click on Export
3. See error

**Expected behavior**
I'd expect it to export so I can backup and restore my data on a new phone

**Comment by josephroqueca** [comment]
I'll take a look into this! I just made some changes to the backend and this report came soon after, so it's likely due to that.

**Comment by CaffGeek** [comment]
Any luck tracking down the cause @josephroqueca ? I notice it doesn't work on either of my phones...the new one also fails.

**Comment by josephroqueca** [comment]
@CaffGeek Sorry it's taken me so long to respond. Are you still experiencing this issue? I can't reproduce it.

**Comment by josephroqueca** [comment]
I've reverted the server to a previous version that should be working. Let me know if you're still experiencing issues.
